x = 42
# if x > 1:
#     y = 666
#
# print(y) # 666
#
def magic():
    x = 43

magic()
print(x)

# try:
#     int("ala")
# except ValueError as e:
#     print(e)
#
# print(e)
# try jest wyjątkiem, bo co do zasady blok nie tworzy zasięgu poza try